// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var buvid3Data = Buvid3Data.FromJson(jsonString);

namespace QuickType.LazyComment.Buvid3
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Buvid3Data
    {
        [JsonProperty("code")]
        public long Code { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("buvid")]
        public string Buvid { get; set; }
    }

    public partial class Buvid3Data
    {
        public static Buvid3Data FromJson(string json) => JsonConvert.DeserializeObject<Buvid3Data>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Buvid3Data self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}